package com.budgetplanner.categorization;

import java.util.HashMap;

public class TxnCategorizationUtil {
	
	private static HashMap<String, TransactionCategory> txnCategoryIndex;

	private static TxnCategorizationUtil instance;
	
	private TxnCategorizationUtil() {
		// populate the index
		txnCategoryIndex = new HashMap<>();
		
		txnCategoryIndex.put("SAINSBURY", TransactionCategory.FOOD_AND_DRINK);
		txnCategoryIndex.put("ASDA", TransactionCategory.FOOD_AND_DRINK);
		txnCategoryIndex.put("ICELAND", TransactionCategory.FOOD_AND_DRINK);
		txnCategoryIndex.put("ALDI", TransactionCategory.FOOD_AND_DRINK);		
		txnCategoryIndex.put("MORRISONS", TransactionCategory.FOOD_AND_DRINK);
		txnCategoryIndex.put("LIDL", TransactionCategory.FOOD_AND_DRINK);
		txnCategoryIndex.put("SCOTMID", TransactionCategory.FOOD_AND_DRINK);
		txnCategoryIndex.put("MARKS&SPENCER", TransactionCategory.FOOD_AND_DRINK);
		txnCategoryIndex.put("TESCO STORES", TransactionCategory.FOOD_AND_DRINK);
		txnCategoryIndex.put("GREGGS", TransactionCategory.FOOD_AND_DRINK);
		txnCategoryIndex.put("BURGER", TransactionCategory.FOOD_AND_DRINK);
		txnCategoryIndex.put("PATISSERIE", TransactionCategory.FOOD_AND_DRINK);
		txnCategoryIndex.put("SUBWAY", TransactionCategory.FOOD_AND_DRINK);
		txnCategoryIndex.put("MCDONALDS", TransactionCategory.FOOD_AND_DRINK);
		txnCategoryIndex.put("MCDONALD'S", TransactionCategory.FOOD_AND_DRINK);
		txnCategoryIndex.put("FAT JACKETS", TransactionCategory.FOOD_AND_DRINK);
		txnCategoryIndex.put("DELI", TransactionCategory.FOOD_AND_DRINK);
		txnCategoryIndex.put("ZUCCA", TransactionCategory.FOOD_AND_DRINK);
		txnCategoryIndex.put("JUST EAT", TransactionCategory.FOOD_AND_DRINK);
		txnCategoryIndex.put("HOLLAND AND BARRETT", TransactionCategory.FOOD_AND_DRINK);
		txnCategoryIndex.put("FARMFOODS", TransactionCategory.FOOD_AND_DRINK);
		txnCategoryIndex.put("WAITROSE", TransactionCategory.FOOD_AND_DRINK);
		txnCategoryIndex.put("NESPRESSO", TransactionCategory.FOOD_AND_DRINK);
		txnCategoryIndex.put("NANDOS", TransactionCategory.FOOD_AND_DRINK);
		txnCategoryIndex.put("NETTO", TransactionCategory.FOOD_AND_DRINK);
		txnCategoryIndex.put("PIZZA EXPRESS", TransactionCategory.FOOD_AND_DRINK);
		txnCategoryIndex.put("BURGER KING", TransactionCategory.FOOD_AND_DRINK);
		txnCategoryIndex.put("LAS IGUANAS", TransactionCategory.FOOD_AND_DRINK);
		txnCategoryIndex.put("SLUG & LETTUCE", TransactionCategory.FOOD_AND_DRINK);
		txnCategoryIndex.put("SLUG AND LETTUCE", TransactionCategory.FOOD_AND_DRINK);
		txnCategoryIndex.put("HARVESTER", TransactionCategory.FOOD_AND_DRINK);
		txnCategoryIndex.put("COSTA", TransactionCategory.FOOD_AND_DRINK);
		txnCategoryIndex.put("KFC", TransactionCategory.FOOD_AND_DRINK);
		txnCategoryIndex.put("KRISPY KREME", TransactionCategory.FOOD_AND_DRINK);
		txnCategoryIndex.put("JAMIES ITALIAN", TransactionCategory.FOOD_AND_DRINK);
		txnCategoryIndex.put("DONUTS", TransactionCategory.FOOD_AND_DRINK);
		txnCategoryIndex.put("MILLIES", TransactionCategory.FOOD_AND_DRINK);
		txnCategoryIndex.put("MUFFIN BREAK", TransactionCategory.FOOD_AND_DRINK);
		txnCategoryIndex.put("PIZZA HUT", TransactionCategory.FOOD_AND_DRINK);
		txnCategoryIndex.put("TONY MACARONI", TransactionCategory.FOOD_AND_DRINK);
		txnCategoryIndex.put("SPUDULIKE", TransactionCategory.FOOD_AND_DRINK);
		txnCategoryIndex.put("STARBUCKS", TransactionCategory.FOOD_AND_DRINK);
		txnCategoryIndex.put("CO-OP", TransactionCategory.FOOD_AND_DRINK);
		txnCategoryIndex.put("COOP", TransactionCategory.FOOD_AND_DRINK);
		txnCategoryIndex.put("WAITROSE", TransactionCategory.FOOD_AND_DRINK);
		txnCategoryIndex.put("ASK ITALIAN", TransactionCategory.FOOD_AND_DRINK);
		txnCategoryIndex.put("CHARGRILL", TransactionCategory.FOOD_AND_DRINK);
		txnCategoryIndex.put("PREZZO", TransactionCategory.FOOD_AND_DRINK);
		txnCategoryIndex.put("PRETZEL", TransactionCategory.FOOD_AND_DRINK);
		txnCategoryIndex.put("PRET A MANGER", TransactionCategory.FOOD_AND_DRINK);
		txnCategoryIndex.put("SWEET SHOP", TransactionCategory.FOOD_AND_DRINK);
		txnCategoryIndex.put("QUA ITALIAN", TransactionCategory.FOOD_AND_DRINK);
		txnCategoryIndex.put("LOCH FYNE", TransactionCategory.FOOD_AND_DRINK);
		txnCategoryIndex.put("AUNTIE ANNE", TransactionCategory.FOOD_AND_DRINK);
		txnCategoryIndex.put("BARBURRITO", TransactionCategory.FOOD_AND_DRINK);
		txnCategoryIndex.put("COFFEE", TransactionCategory.FOOD_AND_DRINK);
		txnCategoryIndex.put("MUFFIN", TransactionCategory.FOOD_AND_DRINK);
		txnCategoryIndex.put("CHOW STREET KITCHEN", TransactionCategory.FOOD_AND_DRINK);
		txnCategoryIndex.put("YO SUSHI", TransactionCategory.FOOD_AND_DRINK);
		txnCategoryIndex.put("HARRY RAMSDEN", TransactionCategory.FOOD_AND_DRINK);
		txnCategoryIndex.put("COOKIE", TransactionCategory.FOOD_AND_DRINK);
		txnCategoryIndex.put("BEN&JERRY", TransactionCategory.FOOD_AND_DRINK);
		txnCategoryIndex.put("NATUZZI", TransactionCategory.FOOD_AND_DRINK);
		txnCategoryIndex.put("BEN & JERRY", TransactionCategory.FOOD_AND_DRINK);
		txnCategoryIndex.put("BOOST", TransactionCategory.FOOD_AND_DRINK);
		txnCategoryIndex.put("CAFE", TransactionCategory.FOOD_AND_DRINK);
		txnCategoryIndex.put("CAFFE", TransactionCategory.FOOD_AND_DRINK);
		txnCategoryIndex.put("CARLUCCIOS", TransactionCategory.FOOD_AND_DRINK);
		txnCategoryIndex.put("APPLEBEES", TransactionCategory.FOOD_AND_DRINK);
		txnCategoryIndex.put("QUIZNOS", TransactionCategory.FOOD_AND_DRINK);
		txnCategoryIndex.put("CHILANGA", TransactionCategory.FOOD_AND_DRINK);
		txnCategoryIndex.put("CHIQUITOS", TransactionCategory.FOOD_AND_DRINK);
		txnCategoryIndex.put("CHAO BABY", TransactionCategory.FOOD_AND_DRINK);
		txnCategoryIndex.put("BUFFET", TransactionCategory.FOOD_AND_DRINK);
		txnCategoryIndex.put("PANCAKE EXPRESS", TransactionCategory.FOOD_AND_DRINK);
		txnCategoryIndex.put("PANDA EXPRESS", TransactionCategory.FOOD_AND_DRINK);
		txnCategoryIndex.put("O'BRIAN'S", TransactionCategory.FOOD_AND_DRINK);
		txnCategoryIndex.put("OBRIANS", TransactionCategory.FOOD_AND_DRINK);
		txnCategoryIndex.put("FRANKIE AND BENNY", TransactionCategory.FOOD_AND_DRINK);
		
		txnCategoryIndex.put("TESCO SAVER", TransactionCategory.SAVINGS_AND_INVESTMENTS);
		
		txnCategoryIndex.put("ADMIRAL", TransactionCategory.INSURANCE);
		txnCategoryIndex.put("CHURCHILL", TransactionCategory.INSURANCE);
		txnCategoryIndex.put("COVERFORYOU", TransactionCategory.INSURANCE);

		txnCategoryIndex.put("Q PARK", TransactionCategory.COMMUTING);
		txnCategoryIndex.put("DVLA", TransactionCategory.COMMUTING);
		txnCategoryIndex.put("M O T", TransactionCategory.COMMUTING);
		txnCategoryIndex.put("ABELLIO", TransactionCategory.COMMUTING);
		txnCategoryIndex.put("SCOTRAIL", TransactionCategory.COMMUTING);
		txnCategoryIndex.put("KNOX BROTHERS", TransactionCategory.COMMUTING);
		txnCategoryIndex.put("NCP", TransactionCategory.COMMUTING);
		
		txnCategoryIndex.put("AMAZON", TransactionCategory.FUN);
		txnCategoryIndex.put("BINGO", TransactionCategory.FUN);
		txnCategoryIndex.put("CASINO", TransactionCategory.FUN);
		txnCategoryIndex.put("GAMESTATION", TransactionCategory.FUN);
		txnCategoryIndex.put("GAMES WORKSHOP", TransactionCategory.FUN);
		txnCategoryIndex.put("WARHAMMER", TransactionCategory.FUN);
		txnCategoryIndex.put("HOLLYWOOD BOWL", TransactionCategory.FUN);
		txnCategoryIndex.put("BOWLING", TransactionCategory.FUN);
		txnCategoryIndex.put("CEX", TransactionCategory.FUN);
		txnCategoryIndex.put("CINEMA", TransactionCategory.FUN);
		txnCategoryIndex.put("SEA LIFE", TransactionCategory.FUN);
		txnCategoryIndex.put("PAYPAL", TransactionCategory.FUN);
		txnCategoryIndex.put("OLYMPIA PETS", TransactionCategory.FUN);
		txnCategoryIndex.put("RED5", TransactionCategory.FUN);
		txnCategoryIndex.put("MODELZONE", TransactionCategory.FUN);
		txnCategoryIndex.put("NAMCO FUNSCAPE", TransactionCategory.FUN);
		txnCategoryIndex.put("AIRSPACE", TransactionCategory.FUN);
		txnCategoryIndex.put("GLASGOW SCIENCE CENTRE", TransactionCategory.FUN);
		txnCategoryIndex.put("LAZER QUEST", TransactionCategory.FUN);
		txnCategoryIndex.put("LASER QUEST", TransactionCategory.FUN);
		txnCategoryIndex.put("ELVIS BAR", TransactionCategory.FUN);
		txnCategoryIndex.put("NOTONTHEHIGHSTREET.COM", TransactionCategory.FUN);
		txnCategoryIndex.put("PETS AT HOME", TransactionCategory.FUN);
		txnCategoryIndex.put("ENTRYCENTRAL", TransactionCategory.FUN);
		txnCategoryIndex.put("WH SMITH", TransactionCategory.FUN);
		txnCategoryIndex.put("HMV", TransactionCategory.FUN);
		txnCategoryIndex.put("CLINTON CARDS", TransactionCategory.FUN);
		txnCategoryIndex.put("DISNEY STORE", TransactionCategory.FUN);
		txnCategoryIndex.put("HMV", TransactionCategory.FUN);
		txnCategoryIndex.put("BETFAIR", TransactionCategory.FUN);
		txnCategoryIndex.put("LADBROKES", TransactionCategory.FUN);
		txnCategoryIndex.put("PADDY POWER", TransactionCategory.FUN);
		txnCategoryIndex.put("CORAL", TransactionCategory.FUN);
		txnCategoryIndex.put("MAPLIN", TransactionCategory.FUN);
		txnCategoryIndex.put("TICKETMASTER", TransactionCategory.FUN);
		txnCategoryIndex.put("ODEON", TransactionCategory.FUN);
		txnCategoryIndex.put("CINEWORLD", TransactionCategory.FUN);
		txnCategoryIndex.put("WATERSTONES", TransactionCategory.FUN);
		txnCategoryIndex.put("MENKIND", TransactionCategory.FUN);
		txnCategoryIndex.put("BLACKWELL", TransactionCategory.FUN);
		txnCategoryIndex.put("BOOKS", TransactionCategory.FUN);
		txnCategoryIndex.put("BANG AND OLUFSEN", TransactionCategory.FUN);
		txnCategoryIndex.put("BANG & OLUFSEN", TransactionCategory.FUN);
		txnCategoryIndex.put("HADDOWS", TransactionCategory.FUN);
		txnCategoryIndex.put("ONEOONE", TransactionCategory.FUN);
		txnCategoryIndex.put("LIQUOR", TransactionCategory.FUN);
		txnCategoryIndex.put("WINE", TransactionCategory.FUN);
		
		txnCategoryIndex.put("BUILD A BEAR", TransactionCategory.FAMILY);
		txnCategoryIndex.put("EARLY LEARNING CENTRE", TransactionCategory.FAMILY);
		txnCategoryIndex.put("ELC", TransactionCategory.FAMILY);
		txnCategoryIndex.put("HAMLEYS", TransactionCategory.FAMILY);
		txnCategoryIndex.put("MAMAS AND PAPAS", TransactionCategory.FAMILY);
		txnCategoryIndex.put("MAMAS & PAPAS", TransactionCategory.FAMILY);
		txnCategoryIndex.put("LEGO STORE", TransactionCategory.FAMILY);
		txnCategoryIndex.put("TOY SHOP", TransactionCategory.FAMILY);
		txnCategoryIndex.put("MOTHERCARE", TransactionCategory.FAMILY);
		
		txnCategoryIndex.put("HARLANDS", TransactionCategory.HEALTH_AND_BEAUTY);
		txnCategoryIndex.put("ARRAN AROMATICS", TransactionCategory.HEALTH_AND_BEAUTY);
		txnCategoryIndex.put("ACCESSORIES", TransactionCategory.HEALTH_AND_BEAUTY);
		txnCategoryIndex.put("BARE MINERALS", TransactionCategory.HEALTH_AND_BEAUTY);
		txnCategoryIndex.put("CRABTREE AND EVELYN", TransactionCategory.HEALTH_AND_BEAUTY);
		txnCategoryIndex.put("BODYCARE", TransactionCategory.HEALTH_AND_BEAUTY);
		txnCategoryIndex.put("NAIL BAR", TransactionCategory.HEALTH_AND_BEAUTY);
		txnCategoryIndex.put("BEAUTY", TransactionCategory.HEALTH_AND_BEAUTY);
		txnCategoryIndex.put("MOLTEN BROWN", TransactionCategory.HEALTH_AND_BEAUTY);
		txnCategoryIndex.put("RAINBOW ROOM", TransactionCategory.HEALTH_AND_BEAUTY);
		txnCategoryIndex.put("DOLLAND AND AITCHISON", TransactionCategory.HEALTH_AND_BEAUTY);
		txnCategoryIndex.put("DOLLAND & AITCHISON", TransactionCategory.HEALTH_AND_BEAUTY);
		txnCategoryIndex.put("BOOTS", TransactionCategory.HEALTH_AND_BEAUTY);
		txnCategoryIndex.put("CYCLE", TransactionCategory.HEALTH_AND_BEAUTY);
		txnCategoryIndex.put("OPTICAL EXPRESS", TransactionCategory.HEALTH_AND_BEAUTY);
		txnCategoryIndex.put("SPECSAVERS", TransactionCategory.HEALTH_AND_BEAUTY);
		txnCategoryIndex.put("DENTIST", TransactionCategory.HEALTH_AND_BEAUTY);
		txnCategoryIndex.put("SUPERCUTS", TransactionCategory.HEALTH_AND_BEAUTY);
		txnCategoryIndex.put("BARBER", TransactionCategory.HEALTH_AND_BEAUTY);
		txnCategoryIndex.put("SUPERDRUG", TransactionCategory.HEALTH_AND_BEAUTY);
		txnCategoryIndex.put("PERFUME SHOP", TransactionCategory.HEALTH_AND_BEAUTY);
		txnCategoryIndex.put("VISION EXPRESS", TransactionCategory.HEALTH_AND_BEAUTY);
		txnCategoryIndex.put("BEAUTY CRAZE", TransactionCategory.HEALTH_AND_BEAUTY);
		txnCategoryIndex.put("ACCESSORIZE", TransactionCategory.HEALTH_AND_BEAUTY);
		txnCategoryIndex.put("BOBBI BROWN", TransactionCategory.HEALTH_AND_BEAUTY);
		txnCategoryIndex.put("SALON", TransactionCategory.HEALTH_AND_BEAUTY);
		txnCategoryIndex.put("OPTICIAN", TransactionCategory.HEALTH_AND_BEAUTY);
		txnCategoryIndex.put("HERBAL INN", TransactionCategory.HEALTH_AND_BEAUTY);
		txnCategoryIndex.put("HERSTYLER", TransactionCategory.HEALTH_AND_BEAUTY);
		txnCategoryIndex.put("JULIAN GRAVES", TransactionCategory.HEALTH_AND_BEAUTY);
		txnCategoryIndex.put("LOCCITANE", TransactionCategory.HEALTH_AND_BEAUTY);
		txnCategoryIndex.put("L'OCCITANE", TransactionCategory.HEALTH_AND_BEAUTY);
		txnCategoryIndex.put("LUSH", TransactionCategory.HEALTH_AND_BEAUTY);
		txnCategoryIndex.put("NAILS INC", TransactionCategory.HEALTH_AND_BEAUTY);
		txnCategoryIndex.put("MALIKA", TransactionCategory.HEALTH_AND_BEAUTY);
		txnCategoryIndex.put("NEAL'S YARD REMEDIES", TransactionCategory.HEALTH_AND_BEAUTY);
		txnCategoryIndex.put("NEALS YARD REMEDIES", TransactionCategory.HEALTH_AND_BEAUTY);

		txnCategoryIndex.put("BRANTANO", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("REEBOK", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("DESIGUAL", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("CATH KIDSTON", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("DIESEL", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("GAP", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("GANT", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("JJB SPORTS", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("M & CO", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("M AND CO", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("SOCK SHOP", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("SOLE TRADER", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("O'NEILL", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("RADLEY", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("ACHILLES HEEL", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("RUNNERS NEED", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("RUSSELL AND BROMLEY", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("SKETCHERS", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("SIMPLY BE", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("RUSSELL & BROMLEY", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("SCHOLL", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("SCHUH", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("RALPH LAUREN", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("PRICELESS SHOES", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("ASOS", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("PULL&BEAR", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("PUMA", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("QUIKSILVER", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("PUNKY FISH", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("OAKLEY", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("MADHOUSE", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("MACHKA", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("LA SENZA", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("LACOSTE", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("LIPSY", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("LOUIS VUITTON", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("KAREN MILLEN", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("BOOTMAKER", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("KOOKAI", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("KURT GEIGER", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("HUGO BOSS", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("JEANS", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("INTERNACIONALE", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("INTIMISSIMI", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("PEAK PERFORMANCE", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("MICHAEL KORS", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("MILLETS", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("PEACOCKS", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("PAUL SMITH", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("JACK JONES", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("JACK WILLS", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("JACQUES VERT", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("MENSWEAR", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("JAEGER", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("HOLLISTER", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("LEVIS", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("LEVI'S", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("HARVEY NICHOLS", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("FOOT LOCKER", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("HENLEYS", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("HAWKSHEAD", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("HENRI LLOYD", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("FOOTASYLUM", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("FOREVER 21", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("G-STAR", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("MODA IN PELLE", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("DKNY", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("FORMARINA", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("FRED PERRY", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("FASHON", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("BERGHAUS", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("FAT FACE", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("CALVIN KLEIN", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("DR MARTENS", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("CAMEL ACTIVE", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("BERSHKA", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("CLOTHING", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("BENCH", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("COTSWOLD", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("COTTON TRADERS", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("CROCS", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("BARBOUR", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("ZARA", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("WALLIS", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("APRICOT", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("AQUASCUTUM", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("ARMANI", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("ASICS", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("BURBERRY", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("CHARLES KINKARD", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("SPORTS DIRECT", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("OFFICERS CLUB", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("BEALES", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("RUN4IT", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("NEW LOOK", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("OASIS", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("MISS SELFRIDGE", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("MONSOON", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("MOUNTAIN WAREHOUSE", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("JANE NORMAN", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("BARONJON", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("JDSPORTS", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("DOROTHY PERKINS", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("DUNE SHOES", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("ALL SAINTS", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("TK MAXX", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("ECCO", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("ELLIS BRIDGHAM", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("ELVIS JESUS", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("ESPRIT", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("AMERICAN APPAREL", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("TOPSHOP", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("TOPMAN", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("COAST", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("COLUMBIA", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("TRESPASS", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("USC", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("RIVER ISLAND", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("ANN SUMMERS", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("BARRATTS", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("BANANA REPUBLIC", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("BON MARCHE", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("ASPECTO", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("AUSTIN REED", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("ANN HARVEY", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("APPY FEET", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("PEPPERBERRY", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("ORLEBAR BROWN", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("SHOE ZONE", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("SELFRIDGES", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("SHERUNSSHERUNS", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("BONMARCHE", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("BURTON", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("CLARKS", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("GUESS", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("DEICHMANN", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("FRENCH CONNECTION", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("H&M", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("H AND M", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("ADIDAS", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("NIKE", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("ADAMS", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("ALFRED DUNHILL", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("CARZO PAZOLINI", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("GUCCI", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("PRADA", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("PRIMARK", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("GEOX", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("GERRY WEBER", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("GLEVES AND HAWKES", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("GLEVES & HAWKES", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("CHARLES TYRWHITT", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("LINZI SHOES", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("LK BENNETT", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("MASSIMO DUTTI", TransactionCategory.CLOTHES);
		txnCategoryIndex.put("MATALAN", TransactionCategory.CLOTHES);
		
		txnCategoryIndex.put("CARDS GALORE", TransactionCategory.BIG_ONE_OFFS);
		txnCategoryIndex.put("CHARLES FISH", TransactionCategory.BIG_ONE_OFFS);
		txnCategoryIndex.put("GODIVA", TransactionCategory.BIG_ONE_OFFS);
		txnCategoryIndex.put("BIJOU BRIGITTE", TransactionCategory.BIG_ONE_OFFS);
		txnCategoryIndex.put("THORNTONS", TransactionCategory.BIG_ONE_OFFS);
		txnCategoryIndex.put("ERNEST JONES", TransactionCategory.BIG_ONE_OFFS);
		txnCategoryIndex.put("BEAVERBROOKS", TransactionCategory.BIG_ONE_OFFS);
		txnCategoryIndex.put("WARREN JAMES", TransactionCategory.BIG_ONE_OFFS);
		txnCategoryIndex.put("SWAROVSKI", TransactionCategory.BIG_ONE_OFFS);
		txnCategoryIndex.put("ROLEX", TransactionCategory.BIG_ONE_OFFS);
		txnCategoryIndex.put("OMEGA BOUTIQUE", TransactionCategory.BIG_ONE_OFFS);
		txnCategoryIndex.put("GOING PLACES", TransactionCategory.BIG_ONE_OFFS);
		txnCategoryIndex.put("GOLDSMITHS", TransactionCategory.BIG_ONE_OFFS);
		txnCategoryIndex.put("H.SAMUEL", TransactionCategory.BIG_ONE_OFFS);
		txnCategoryIndex.put("FIRST CHOICE", TransactionCategory.BIG_ONE_OFFS);
		txnCategoryIndex.put("TUI", TransactionCategory.BIG_ONE_OFFS);
		txnCategoryIndex.put("THOMSON", TransactionCategory.BIG_ONE_OFFS);
		txnCategoryIndex.put("THOMAS COOK", TransactionCategory.BIG_ONE_OFFS);
		txnCategoryIndex.put("CALENDAR CLUB", TransactionCategory.BIG_ONE_OFFS);
		txnCategoryIndex.put("CARD FACTORY", TransactionCategory.BIG_ONE_OFFS);
		txnCategoryIndex.put("CLINTONS", TransactionCategory.BIG_ONE_OFFS);
		txnCategoryIndex.put("EASYJET", TransactionCategory.BIG_ONE_OFFS);
		txnCategoryIndex.put("RYANAIR", TransactionCategory.BIG_ONE_OFFS);
		txnCategoryIndex.put("JET2", TransactionCategory.BIG_ONE_OFFS);
		txnCategoryIndex.put("BRITISH AIRWAYS", TransactionCategory.BIG_ONE_OFFS);
		txnCategoryIndex.put("AZENDI", TransactionCategory.BIG_ONE_OFFS);
		txnCategoryIndex.put("JEWELLER", TransactionCategory.BIG_ONE_OFFS);
		txnCategoryIndex.put("PANDORA", TransactionCategory.BIG_ONE_OFFS);
		txnCategoryIndex.put("CADENZZA", TransactionCategory.BIG_ONE_OFFS);
		txnCategoryIndex.put("CLAYBROOKS", TransactionCategory.BIG_ONE_OFFS);
		txnCategoryIndex.put("HOTEL CHOCOLAT", TransactionCategory.BIG_ONE_OFFS);
		txnCategoryIndex.put("TRAVELODGE", TransactionCategory.BIG_ONE_OFFS);
		txnCategoryIndex.put("PREMIER INN", TransactionCategory.BIG_ONE_OFFS);
		txnCategoryIndex.put("LEONIDAS", TransactionCategory.BIG_ONE_OFFS);
		txnCategoryIndex.put("LESLIE DAVIS", TransactionCategory.BIG_ONE_OFFS);
		txnCategoryIndex.put("LINKS OF LONDON", TransactionCategory.BIG_ONE_OFFS);
		
		txnCategoryIndex.put("FURNITURE", TransactionCategory.HOME);
		txnCategoryIndex.put("IKEA", TransactionCategory.HOME);
		txnCategoryIndex.put("CARPET RIGHT", TransactionCategory.HOME);
		txnCategoryIndex.put("DFS", TransactionCategory.HOME);
		txnCategoryIndex.put("SCS", TransactionCategory.HOME);
		txnCategoryIndex.put("DREAMS", TransactionCategory.HOME);
		txnCategoryIndex.put("WICKES", TransactionCategory.HOME);
		txnCategoryIndex.put("SOFA", TransactionCategory.HOME);
		txnCategoryIndex.put("ROBERT DYAS", TransactionCategory.HOME);
		txnCategoryIndex.put("HOMEBASE", TransactionCategory.HOME);
		txnCategoryIndex.put("PHONES4U", TransactionCategory.HOME);
		txnCategoryIndex.put("SCREWFIX", TransactionCategory.HOME);
		txnCategoryIndex.put("PHONES 4 U", TransactionCategory.HOME);
		txnCategoryIndex.put("HABITAT", TransactionCategory.HOME);
		txnCategoryIndex.put("HARVEYS", TransactionCategory.HOME);
		txnCategoryIndex.put("CHITTER CHATTER", TransactionCategory.HOME);
		txnCategoryIndex.put("DUNELM MILL", TransactionCategory.HOME);
		txnCategoryIndex.put("LEBARA", TransactionCategory.HOME);
		txnCategoryIndex.put("COMET", TransactionCategory.HOME);
		txnCategoryIndex.put("CANDLE", TransactionCategory.HOME);
		txnCategoryIndex.put("ORANGE", TransactionCategory.HOME);
		txnCategoryIndex.put("CARPHONE WAREHOUSE", TransactionCategory.HOME);
		txnCategoryIndex.put("BRITISH GAS", TransactionCategory.HOME);
		txnCategoryIndex.put("BRIGHT HOUSE", TransactionCategory.HOME);
		txnCategoryIndex.put("BRIGHTHOUSE", TransactionCategory.HOME);
		txnCategoryIndex.put("EDF ENERGY", TransactionCategory.HOME);
		txnCategoryIndex.put("BNQ", TransactionCategory.HOME);
		txnCategoryIndex.put("B&Q", TransactionCategory.HOME);
		txnCategoryIndex.put("NPOWER", TransactionCategory.HOME);
		txnCategoryIndex.put("HEATING CONTROLS", TransactionCategory.HOME);
		txnCategoryIndex.put("GIFFGAFF", TransactionCategory.HOME);
		txnCategoryIndex.put("TOOLSTATION", TransactionCategory.HOME);
		txnCategoryIndex.put("SOUTH LANARKSHIRE", TransactionCategory.HOME);
		txnCategoryIndex.put("B AND Q", TransactionCategory.HOME);
		txnCategoryIndex.put("VIRGIN MOBILE", TransactionCategory.HOME);
		txnCategoryIndex.put("CURRYS", TransactionCategory.HOME);
		txnCategoryIndex.put("PC WORLD", TransactionCategory.HOME);
		txnCategoryIndex.put("VIRGIN MEDIA PYNTS", TransactionCategory.HOME);
		txnCategoryIndex.put("SCGAS", TransactionCategory.HOME);
		txnCategoryIndex.put("SKY DIGITAL", TransactionCategory.HOME);
		txnCategoryIndex.put("3 MOBILE", TransactionCategory.HOME);
		txnCategoryIndex.put("T MOBILE", TransactionCategory.HOME);
		txnCategoryIndex.put("VODAFONE", TransactionCategory.HOME);
		txnCategoryIndex.put("ALLIED CARPET", TransactionCategory.HOME);
		txnCategoryIndex.put("BLANCO", TransactionCategory.HOME);
		txnCategoryIndex.put("APPLE STORE", TransactionCategory.HOME);
		txnCategoryIndex.put("BARKER AND STONEHOUSE", TransactionCategory.HOME);
		txnCategoryIndex.put("BARKER & STONEHOUSE", TransactionCategory.HOME);
		
		txnCategoryIndex.put("EVERYDAY HERO", TransactionCategory.CHARITY);
		txnCategoryIndex.put("JUSTGIVING", TransactionCategory.CHARITY);
		txnCategoryIndex.put("JUVENILE DIABETES", TransactionCategory.CHARITY);
		txnCategoryIndex.put("WORLD VISION", TransactionCategory.CHARITY);
		txnCategoryIndex.put("OXFAM", TransactionCategory.CHARITY);
		txnCategoryIndex.put("WATER AID", TransactionCategory.CHARITY);
		txnCategoryIndex.put("AGE UK", TransactionCategory.CHARITY);
	}
	
	public static TxnCategorizationUtil getInstance() {
		if (instance == null) {
			instance = new TxnCategorizationUtil();
		}
		return instance;
	}
	
	public TransactionCategory getCategory(String txnDescription) {		
		for (String key : txnCategoryIndex.keySet()) {
			if (txnDescription.toUpperCase().contains(key)) {
				return txnCategoryIndex.get(key);
			}
		}
		
		// Txn Description didn't match any map keys
		return TransactionCategory.MISCELLANEOUS;
	}
	
}
